//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBongDaQuocGia.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAUTHU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CAUTHU()
        {
            this.CHITIETKETQUAs = new HashSet<CHITIETKETQUA>();
            this.DANHSACHCAUTHUGHIBANs = new HashSet<DANHSACHCAUTHUGHIBAN>();
        }
    
        public string MaCT { get; set; }
        public string TenCT { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string MaLoaiCT { get; set; }
        public string GhiChu { get; set; }
        public string MaDB { get; set; }
    
        public virtual LOAICAUTHU LOAICAUTHU { get; set; }
        public virtual DOIBONG DOIBONG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETKETQUA> CHITIETKETQUAs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DANHSACHCAUTHUGHIBAN> DANHSACHCAUTHUGHIBANs { get; set; }
    }
}
