//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBongDaQuocGia.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETKETQUA
    {
        public int MaCTKQ { get; set; }
        public string MaCT { get; set; }
        public string MaDB { get; set; }
        public string LoaiBT { get; set; }
        public Nullable<int> ThoiDiem { get; set; }
        public string MaKQ { get; set; }
    
        public virtual CAUTHU CAUTHU { get; set; }
        public virtual DOIBONG DOIBONG { get; set; }
        public virtual KETQUATHIDAU KETQUATHIDAU { get; set; }
    }
}
