//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBongDaQuocGia.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DANHSACHCAUTHUGHIBAN
    {
        public int MaDSCTGB { get; set; }
        public string MaCT { get; set; }
        public string MaDB { get; set; }
        public string MaLoaiCT { get; set; }
        public Nullable<int> SoBT { get; set; }
    
        public virtual CAUTHU CAUTHU { get; set; }
        public virtual LOAICAUTHU LOAICAUTHU { get; set; }
        public virtual DOIBONG DOIBONG { get; set; }
    }
}
