//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBongDaQuocGia.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class KETQUATHIDAU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KETQUATHIDAU()
        {
            this.CHITIETKETQUAs = new HashSet<CHITIETKETQUA>();
        }
    
        public string MaKQ { get; set; }
        public Nullable<int> BTDoi1 { get; set; }
        public Nullable<int> BTDoi2 { get; set; }
        public string MaTD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETKETQUA> CHITIETKETQUAs { get; set; }
        public virtual LICHTHIDAU LICHTHIDAU { get; set; }
    }
}
