//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBongDaQuocGia.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLGVDBDQGEntities : DbContext
    {
        public QLGVDBDQGEntities()
            : base("name=QLGVDBDQGEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BANGXEPHANG> BANGXEPHANGs { get; set; }
        public virtual DbSet<CAUTHU> CAUTHUs { get; set; }
        public virtual DbSet<CHITIETKETQUA> CHITIETKETQUAs { get; set; }
        public virtual DbSet<DANHSACHCAUTHUGHIBAN> DANHSACHCAUTHUGHIBANs { get; set; }
        public virtual DbSet<DOIBONG> DOIBONGs { get; set; }
        public virtual DbSet<KETQUATHIDAU> KETQUATHIDAUs { get; set; }
        public virtual DbSet<LICHTHIDAU> LICHTHIDAUs { get; set; }
        public virtual DbSet<LOAICAUTHU> LOAICAUTHUs { get; set; }
        public virtual DbSet<VONGDAU> VONGDAUs { get; set; }
    }
}
